### PR TITLE
Revert "Enhancements"

### PR DESCRIPTION
**Pull request by aureamunoz**
Reverts snowdrop/quarkus-spring-data-jpa-api#2 could you please take a look to the license please @geoand ?

### CODE REVIEW

**Comment by aureamunoz** [comment]
cc @gytis

**Comment by gytis** [comment]
Why is this being reverted?

**Comment by aureamunoz** [comment]
Because I merged it by mistake before review the license part

**Comment by aureamunoz** [comment]
Sorry, this is not correct. Wrong manipulation

**Pull request closed without merging**
